### ISSUE TITLE
Design a logo for SharpClock

### ISSUE THREAD

**Issue by fringvil** [FrejBjornsson/SharpClock#1]
# Design a logo for SharpClock :star:

- Modern and minimalistic logo.

- Dimensions should be at least 512x512 pixels.

If we choose your logo, you should send us a PNG and a work file (.PSD, .AI, etc.)

_By submitting you agree to give us full right to use all files you send in this open-source project._

**Comment by calderaricaio** [comment]
Hi! Here's my suggestion. It can be used as a simple logo in many formats. Let me know if you like it I can export it in many sizes and send all source files.

![Screen Shot 2020-10-15 at 20 49 48](https://user-images.githubusercontent.com/542722/96197305-090eb780-0f28-11eb-8025-35bee5b7ad73.png)

**Comment by fringvil** [comment]
**Looks great!** Just what i was looking for 😄 
- We need a banner for GitHub (in the readme) and icons for upcoming project site and the app. Send the sizes you think fits the purpose best. 

## If you want this contribution counting towards Hacktoberfest you should commit the files via a Pull Request preferably in a folder called Design. If not possible tell me how you want to send the files. 👍

**Comment by calderaricaio** [comment]
Cool! I will send the files via PR soon, just give me some time to prepare
the files! Thanks!

**Comment by fringvil** [comment]
Great. No hurry! Thanks for contributing.

**Comment by calderaricaio** [comment]
Hi @FrejBjornsson here's the PR: https://github.com/FrejBjornsson/SharpClock/pull/3
