### ISSUE TITLE
Add Timezone Picker

### ISSUE THREAD

**Issue by fringvil** [FrejBjornsson/SharpClock#2]
# Add a Timezone Picker 🔧 
- Preferably a dropdown menu below clock 
- Add some major timezones e.g. London, New York, Shanghai... 

# How To
- Fork this repo. 🍴 
- Clone it into Visual Studio. 
- Commit your changes. (describe what you changed) 
- Push. 
- Make a Pull Request (compare between forks), 
- Exclude your development environment .vs files and submit Pull Request 

Happy coding! 🌟

**Comment by ralphmcintyre** [comment]
@FrejBjornsson I can take this one!

**Comment by fringvil** [comment]
Great!

**Comment by fringvil** [comment]
There was some changes in the code be sure you have your repo up to date @ralphjmcintyre

**Comment by fringvil** [comment]
Thank you very much!  

I adjusted some things because it did not show up on my screen properly.  It works now, thanks for your contribution! 💯
